### ISSUE TITLE
cannot be installed w Ruby 1.9.3  / Rails 3.1.1

### ISSUE THREAD

**Issue by ghost** [pixels-and-bits/jabe#1]
env: Rails 3.1.1 / Ruby 1.9.3 / MacOSX 10.7.2 Lion / 64-bits

An error occured while installing ffi (0.6.3), and Bundler cannot continue.
compile error ...

compiling StructLayout.c
StructLayout.c: In function ‘struct_layout_initialize’:
StructLayout.c:343: warning: implicit conversion shortens 64-bit value into a 32-bit value
StructLayout.c:363: error: lvalue required as left operand of assignment
make: **\* [StructLayout.o] Error 1

ffi 0.6.3 is a very old version, now running ffi (1.0.10, 1.0.9)

**Comment by UnderpantsGnome** [comment]
erwin- Thanks fort he heads up. I'm going to be away from the computer for the next week so I wont have time to take care of this until after that. If you want to send a pull request I can pull it in.

I know I've been horribly behind on maintenance on this project.

**Comment by UnderpantsGnome** [comment]
Closing, new master resolves this.
