### ISSUE TITLE
Problem installing jabe in current rails 3.2 app.

### ISSUE THREAD

**Issue by lhaig** [pixels-and-bits/jabe#6]
I know that your README says that it is for 3.1 but I was wondering if you would know why I would be getting this error?

NameError (uninitialized constant Jabe::Settings::Rakismet):
  jabe (0.9.0) app/models/jabe/settings.rb:6:in `do_updates'
  jabe (0.9.0) app/models/jabe/settings.rb:13:in`module:Jabe'
  jabe (0.9.0) app/models/jabe/settings.rb:1:in `<top (required)>'
  jabe (0.9.0) app/controllers/jabe/entries_controller.rb:10:in`index'

when trying to connect to the /jabe route in my app?

**Comment by UnderpantsGnome** [comment]
That sounds like the Rakismet gem is missing. Add gem 'rakismet', '>= 1.0.0' to your Gemfile

**Comment by lhaig** [comment]
Closing as I no longer use this
